PayCompute/Controllers/PayController.cs
using Microsoft.AspNetCore.Mvc;
using PayCompute.Models;
using PayCompute.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PayCompute.Controllers
{
    public class PayController : Controller
    {
        private readonly IPayComputationService _payComputationService;
        private readonly IEmployeeService _employeeService;
        private readonly ITaxService taxService;
        public PayController(IPayComputationService payComputationService)
        {
            _payComputationService = payComputationService;
        }
        public IActionResult Index()
        {
            var payRecords = _payComputationService.GetAll().Select(pay => new PaymentRecordIndexViewModel
            {
                Id=pay.Id,
                EmployeeId=pay.EmployeeId,
                FullName=pay.FullName,
                PayDate=pay.PayDate,
                PayMonth=pay.PayMonth,
                TaxYearId=pay.TaxYearId,
                Year=_payComputationService.GetTaxYearById(pay.TaxYearId).YearOfTax,
                TotalEarnings=pay.TotalEarnings,
                TotalDeduction=pay.TotalDeduction,
                NetPayment=pay.NetPayment,
                Employee=pay.Employee
            });
            return View(payRecords);
        }
    }
}

PayCompute/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PayCompute</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.css" />
</head>
<body>
    <div class="container-scroller">
        <nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
            <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
                <a class="navbar-brand brand-logo"><img src="~/images/paycompute.gif" alt="logo"/></a>
            </div>
            <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
                <partial name="_LoginPartial" />
            </div>
        </nav>
        <div class="container-fluid page-body-wrapper">
            <nav class="sidebar sidebar-offcanvas" id="sidebar">
                <ul class="nav">
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#Employee" aria-expanded="false" aria-controls="ui-basic">
                            <i class="fas fa-users fa-lg text-primary" style="margin-right:0.7em"></i>
                            <span class="menu-title">Employee</span>
                            <i class="menu-arrow text-primary"></i>
                        </a>
                        <div class="collapse" id="Employee">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"><a class="nav-link" asp-controller="Employee" asp-action="Create">New Employee</a></li>
                                <li class="nav-item"><a class="nav-link" asp-controller="Employee" asp-action="Index">All Employees</a></li>
                            </ul>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" data-toggle="collapse" href="#Payroll" aria-expanded="false" aria-controls="ui-basic">
                            <i class="fas fa-pound-sign fa-lg text-primary" style="margin-right:0.7em"></i>
                            <span class="menu-title">Payroll</span>
                            <i class="menu-arrow text-primary"></i>
                        </a>
                        <div class="collapse" id="Payroll">
                            <ul class="nav flex-column sub-menu">
                                <li class="nav-item"><a class="nav-link" asp-controller="Pay" asp-action="Create">New Pay</a></li>
                                <li class="nav-item"><a class="nav-link" asp-controller="Pay" asp-action="Index">Payment Records</a></li>
                            </ul>
                        </div>
                    </li>
                </ul>
            </nav>
            <div class="main-panel">
                <partial name="_CookieConsentPartial" />
                <div class="content-wrapper">
                    @RenderBody()
                </div>
                <footer class="footer">
                    <p> &copy; @DateTime.UtcNow.Year - PayCompute - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></p>
                </footer>
            </div>
        </div>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>